example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_xml_by_id
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import register, login_user, logout_user
from wishlist.views import show_ajax, post_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_ajax, name='show_ajax'),
    path('ajax/submit', post_ajax, name='post_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Kausar Meutuwah',
        'last_login': request.COOKIES['last_login'],
        'username': request.user
    }
    return render(request, "wishlist.html", context)


@login_required(login_url='/wishlist/login/')
def show_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Kausar Meutuwah',
        'last_login': request.COOKIES['last_login'],
        'username': request.user
    }
    return render(request, "wishlist_ajax.html")


@login_required(login_url='/wishlist/login/')
def post_ajax(request):
    if request.method == "POST":
        nama_barang = request.POST['nama_barang']
        harga_barang = request.POST['harga_barang']
        deskripsi = request.POST['deskripsi']
        barang_baru = BarangWishlist.objects.create(nama_barang=nama_barang, harga_barang=harga_barang,
                                                    deskripsi=deskripsi)
        return JsonResponse({'error': False, 'msg': 'Successful'})
    return redirect('wishlist:show_ajax')


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))  # membuat response
            response.set_cookie('last_login',
                                str(datetime.datetime.now()))  # membuat cookie last_login dan menambahkannya ke dalam response
            return response

    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    {% block meta %}
    {% endblock meta %}
</head>

<body>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">Kausar Meutuwah - Lab PBP</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSide"
                aria-controls="navbarSide" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSide">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="ml-auto nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {% if request.user.is_anonymous %}
                        Anonymous
                        {% else %}
                        {{ request.user }}
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-sm-end">
                        {% if request.user.is_anonymous %}
                        <li><a class="dropdown-item" href="{% url 'wishlist:login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'wishlist:register' %}">Register</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'wishlist:logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class = "login">

    <h1>Formulir Registrasi</h1>
        <form method="POST" >
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>
                </tr>
            </table>
        </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

{% block meta %}
<title>Wishlist|Kausar</title>
{% endblock meta %}



<br><br>
<table class="table">
    <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
    {% endfor %}
</table>
<h5 class ="text-center">Sesi terakhir login: {{ last_login }}</h5>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

{% block meta %}
<title>Wishlist|Kausar</title>
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">window.CSRF_TOKEN = "{{ csrf_token }}"</script>
{% endblock meta %}

<script>
    function getFormData($form){
        var unindexed_array = $form.serializeArray();
        var indexed_array = {};

        $.map(unindexed_array, function(n, i){
            indexed_array[n['name']] = n['value'];
        });

        return indexed_array;
    }

    $(document).ready(function(){
        $("#add_list").submit(function(e){
            e.preventDefault();
            $(".btnClick").prop('disabled', true);
            $(".btnClick").text('Processing...');
            var $form = $(this);
            var serializedData =  getFormData($form);
            console.log(serializedData)
            $.ajax({
                url: "{% url 'wishlist:post_ajax' %}",
                type: "POST",
                data: serializedData,
                dataType: 'text',
                success: function (data) {
                    $(".btnClick").prop('disabled', false);
                    $(".btnClick").text('Submit');
                    $.getJSON("{% url 'wishlist:show_json' %}", function(json) {
                        // JSON result in `data` variable
                        var tables = [];
                        $.each(json, function(index, val){
                            var row = [];
                            var fields = val.fields
                            row.push("<td>" + String(val.fields.nama_barang) + "</td>");
                            row.push("<td>" + val.fields.harga_barang + "</td>");
                            row.push("<td>" + val.fields.deskripsi + "</td>");
                            tables.push("<tr>" + row.join("") + "</tr>");
                        });
                        document.getElementById("list_barang").innerHTML = tables.join("");
                    });
                }
            });
        });

        $.getJSON("{% url 'wishlist:show_json' %}", function(json) {
            // JSON result in `data` variable
            var tables = [];
            $.each(json, function(index, val){
                var row = [];
                var fields = val.fields
                row.push("<td>" + String(val.fields.nama_barang) + "</td>");
                row.push("<td>" + val.fields.harga_barang + "</td>");
                row.push("<td>" + val.fields.deskripsi + "</td>");
                tables.push("<tr>" + row.join("") + "</tr>");
            });
            document.getElementById("list_barang").innerHTML = tables.join("");
        });
    });


</script>

<!--Navbar-->
<nav class="navbar navbar-expand-sm bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">Kausar Meutuwah - Lab PBP</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSide"
                aria-controls="navbarSide" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSide">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="ml-auto nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {% if request.user.is_anonymous %}
                        Anonymous
                        {% else %}
                        {{ request.user }}
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-sm-end">
                        {% if request.user.is_anonymous %}
                        <li><a class="dropdown-item" href="{% url 'wishlist:login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'wishlist:register' %}">Register</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'wishlist:logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<br><br>

<div class="container">
    <table class="table table-bordered">
        <thead class="table-dark">
        <tr>
            <th scope="col">Nama Barang</th>
            <th scope="col">Harga Barang</th>
            <th scope="col">Deskripsi</th>
        </tr>
        </thead>
        <tbody id="list_barang">
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% comment %} {% for barang in list_barang %}
            <tr>
                <td>{{barang.nama_barang}}</td>
                <td>{{barang.harga_barang}}</td>
                <td>{{barang.deskripsi}}</td>
            </tr>
            {% endfor %} {% endcomment %}
        </tbody>
    </table>



    <form class="mb-5" method="POST" name="barang_form" id="add_list">
        {% csrf_token %}
        <fieldset>
            <h2>Tambah Barang Wishlist</h2>
            <input class="form-control mb-3" type="text" placeholder="Nama barang" name="nama_barang">
            <input class="form-control mb-3" type="number" min="1" step="any" placeholder="Harga barang"
                   name="harga_barang">
            <textarea class="form-control mb-3" rows="3" placeholder="Deskripsi" name="deskripsi"></textarea>
            <button type="submit" class="btn btn-primary btnClick">Submit</button>
        </fieldset>
    </form>
</div>




{% endblock content %}